version: '3.5'
services:
  api01: &api
    hostname: api01
    environment:
      - DB_HOSTNAME=db
    
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api02:
    <<: *api 
    hostname: api02
    environment:
      - DB_HOSTNAME=db
    ports:
      - "8082:8080"

  db:
    image: postgres
    restart: always
    network_mode: host
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: rinha24
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    network_mode: host
    depends_on: 
      - db

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1